language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: mobile-payment-system

after_success:
  - bash <(curl -s https://codecov.io/bash)